### ISSUE TITLE
Error connecting with all tests completed

### ISSUE THREAD

**Issue by llacqie** [sbpp/sourcebans-pp#686]
What are the steps to reproduce this issue?
-------------------------------------------
1. Change server access in web panel

What happens?
-------------
It outputs:
![изображение](https://user-images.githubusercontent.com/46074473/89572248-8aafde00-d831-11ea-8da0-6a8dabc255ed.png)

What were you expecting to happen?
----------------------------------
Done connecting

Any logs, error output, etc.?
----------------------------
![изображение](https://user-images.githubusercontent.com/46074473/89572248-8aafde00-d831-11ea-8da0-6a8dabc255ed.png)
![изображение](https://user-images.githubusercontent.com/46074473/89572475-d06ca680-d831-11ea-89d5-fe807ab1d51b.png)

Any other comments?
-------------------

What versions of software are you using?
----------------------------------------
**Operating System:** Ubuntu 20.04
**SourceBans++ Version:** 1.7.0
**PHP Version:** 7.4-fpm
**MySQL Version:**  10.3.22-MariaDB-1ubuntu1 Ubuntu 20.04
**Link to your project:** 
**Link to a phpinfo() output:** https://github.com/wirke/4issues/blob/master/PHP%207.4.8%20-%20phpinfo().htm

**Comment by crashzk** [comment]
I am having this same problem.

**Operating System:** CentOS 7
**SourceBans++ Version:** 1.7.0 | Git: 1145
**PHP Version:** 7.4.22
**MySQL Version:** 10.2.39-MariaDB
**Link to your project:** https://sourcebans.zkservidores.com/
**Link to a phpinfo() output:** https://zkservidores.com/phpinfo.php

**Comment by rmerac92** [comment]
Any fix?

**Comment by CrazyHackGUT** [comment]
This is already fixed.

**Comment by crashzk** [comment]
> This is already fixed.

Strange, I have version **1.7.0 | Git: 1145** and I have this problem yet.

I'll check the bottom again to see up.

**Comment by CrazyHackGUT** [comment]
Can't reproduce on same version on Windows host.

**Comment by crashzk** [comment]
Really, I checked in depth here, it stopped showing the error.

**Comment by crashzk** [comment]
@CrazyHackGUT update, error still happens.
![image](https://user-images.githubusercontent.com/32937653/136828169-ec68b811-a99b-48fb-ad7c-18bbf983c8cb.png)

I even put the `default` theme and still the error:
![image](https://user-images.githubusercontent.com/32937653/136828340-56012b3e-3857-4e17-b4dc-d8dac523cc55.png)

As you can see, the connection to the servers is all right:
![image](https://user-images.githubusercontent.com/32937653/136828411-8ac1618a-3a5e-4c78-b952-40c3a3888002.png)

I'm running on a **CentOS 7 & PHP 7.4.22**.

https://zkservidores.com/phpinfo.php

**Comment by crashzk** [comment]
I still get this error, but I noticed that when this happens it shows an RCON error in the log.
![image](https://user-images.githubusercontent.com/32937653/141293872-eaf4e55e-294c-407a-b30f-9d751b71c362.png)

I've already checked the RCON, changed it and everything, but nothing.

**Comment by CrazyHackGUT** [comment]
`Connection refused` - looks like RCON port is blocked on firewall.

**Comment by crashzk** [comment]
> `Connection refused` - looks like RCON port is blocked on firewall.

I made some changes to my firewall rules, I'll see if it works, thanks.

**NOTE: I noticed that it lacked UDP & TCP ports released, worse than I had already looked at it, but apparently it went unnoticed. I felt dizzy here.** 🥺
